# -*- coding: utf-8 -*-
"""simon-app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BhFJItrtU-z-glysf68KYOKcDX3N98xi
"""

import random
import time

import streamlit as st

# ----------------------------------------------------------------------------
# Page setup
# ----------------------------------------------------------------------------
st.set_page_config(page_title="Simon Says Memory Game", page_icon="🎮", layout="centered")

COLORS = ["red", "blue", "green", "yellow"]

COLOR_HEX = {
    "red": "#e74c3c",
    "blue": "#3498db",
    "green": "#2ecc71",
    "yellow": "#f1c40f",
}

DIFFICULTY_DELAY = {
    "easy": 6,
    "medium": 3,
    "hard": 1,
}

# ----------------------------------------------------------------------------
# Session state initialization (keeps game state across Streamlit reruns)
# ----------------------------------------------------------------------------
def init_state():
    defaults = {
        "sequence": [],          # computer's growing color sequence
        "player_input": [],      # colors the player has clicked this round
        "round_number": 1,
        "phase": "setup",        # setup -> showing -> guessing -> game_over
        "difficulty": "medium",
        "message": "",
        "show_index": 0,         # which color of the sequence is currently lit
    }
    for key, value in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = value


init_state()


def reset_game():
    st.session_state.sequence = []
    st.session_state.player_input = []
    st.session_state.round_number = 1
    st.session_state.phase = "setup"
    st.session_state.message = ""
    st.session_state.show_index = 0


def start_game():
    st.session_state.sequence = []
    st.session_state.player_input = []
    st.session_state.round_number = 1
    st.session_state.message = ""
    start_new_round()


def start_new_round():
    """Simon adds a new random color and we move into the 'showing' phase."""
    next_color = random.choice(COLORS)
    st.session_state.sequence.append(next_color)
    st.session_state.player_input = []
    st.session_state.show_index = 0
    st.session_state.phase = "showing"


def submit_guess(color):
    st.session_state.player_input.append(color)

    idx = len(st.session_state.player_input) - 1
    # Wrong color guessed early -> game over immediately
    if st.session_state.player_input[idx] != st.session_state.sequence[idx]:
        st.session_state.message = (
            f"Oops! That was not correct. "
            f"The correct sequence was: {', '.join(st.session_state.sequence)}"
        )
        st.session_state.phase = "game_over"
        return

    # Full sequence matched -> advance round
    if len(st.session_state.player_input) == len(st.session_state.sequence):
        st.session_state.message = "Great job! You got it right! 🎉"
        st.session_state.round_number += 1
        start_new_round()


# ----------------------------------------------------------------------------
# UI
# ----------------------------------------------------------------------------
st.title("🎮 Simon Says Memory Game")
st.write("Repeat the sequence of colors that Simon says. Let's see how far you can go!")

# --- Setup phase: choose difficulty and start ---
if st.session_state.phase == "setup":
    st.session_state.difficulty = st.selectbox(
        "Which difficulty do you want?",
        options=["easy", "medium", "hard"],
        index=["easy", "medium", "hard"].index(st.session_state.difficulty),
        help="Easy = colors stay on screen longer. Hard = colors flash by fast.",
    )
    if st.button("Start Game", type="primary"):
        start_game()
        st.rerun()

# --- Showing phase: display the sequence one color at a time ---
elif st.session_state.phase == "showing":
    st.subheader(f"--- ROUND {st.session_state.round_number} ---")
    st.write("Simon says... watch closely!")

    placeholder = st.empty()
    delay = DIFFICULTY_DELAY.get(st.session_state.difficulty, 3)

    for color in st.session_state.sequence:
        with placeholder.container():
            st.markdown(
                f"""
                <div style="
                    background-color:{COLOR_HEX[color]};
                    padding:60px;
                    border-radius:16px;
                    text-align:center;
                    font-size:32px;
                    font-weight:bold;
                    color:white;
                    text-transform:uppercase;">
                    {color}
                </div>
                """,
                unsafe_allow_html=True,
            )
        time.sleep(1)
        placeholder.empty()
        time.sleep(0.3)

    time.sleep(delay)
    st.session_state.phase = "guessing"
    st.rerun()

# --- Guessing phase: player clicks colors in order ---
elif st.session_state.phase == "guessing":
    st.subheader(f"--- ROUND {st.session_state.round_number} ---")
    st.write("Now it's your turn! Click the colors in order.")

    progress = f"{len(st.session_state.player_input)} / {len(st.session_state.sequence)}"
    st.caption(f"Progress: {progress}")

    cols = st.columns(len(COLORS))
    for col, color in zip(cols, COLORS):
        with col:
            if st.button(color.upper(), key=f"btn_{color}", use_container_width=True):
                submit_guess(color)
                st.rerun()

    if st.session_state.message:
        st.info(st.session_state.message)

# --- Game over phase ---
elif st.session_state.phase == "game_over":
    st.subheader("Game Over")
    st.error(st.session_state.message)
    st.write(f"You reached **Round {st.session_state.round_number}**.")
    st.write("Thanks for playing the Simon Says Memory Game! 👋")

    if st.button("Play Again", type="primary"):
        reset_game()
        st.rerun()